apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: comment-service
  labels:
    app: comment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-app
  template:
    metadata:
      labels:
        app: comment-app
    spec:
      containers:
      - name: comment-service
        image: hazemelagaty/comment-service:2.1
        args:
        - bash
        - -c
        - sleep 10; java -jar ./target/Comment-1.0-SNAPSHOT-jar-with-dependencies.jar;
        ports:
        - containerPort: 6380
      restartPolicy: Always
