apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: discussion-service
  labels:
    app: discussion-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discussion-app
  template:
    metadata:
      labels:
        app: discussion-app
    spec:
      containers:
      - name: discussion-service
        image: hazemelagaty/discussion-service:2.1
        args:
        - bash
        - -c
        - sleep 10; java -jar ./target/Discussion-1.0-SNAPSHOT-jar-with-dependencies.jar;
        ports:
        - containerPort: 6380
      restartPolicy: Always
