apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: message-service
  labels:
    app: message-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-app
  template:
    metadata:
      labels:
        app: message-app
    spec:
      containers:
      - name: message-service
        image: hazemelagaty/message-service:2.1
        args:
        - bash
        - -c
        - sleep 10; java -jar ./target/YoutubeBananaMessages-1.0-SNAPSHOT-jar-with-dependencies.jar;
        ports:
        - containerPort: 6380
      restartPolicy: Always
