apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: hazemelagaty/postgres-service:1.0
        ports:
        - containerPort: 5432
      restartPolicy: Always
