apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: post-service
  labels:
    app: post-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-app
  template:
    metadata:
      labels:
        app: post-app
    spec:
      containers:
      - name: post-service
        image: hazemelagaty/post-service:2.1
        args:
        - bash
        - -c
        - sleep 10; java -jar ./target/Post-1.0-SNAPSHOT-jar-with-dependencies.jar;
        ports:
        - containerPort: 6380
      restartPolicy: Always
