apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: video-service
  labels:
    app: video-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-app
  template:
    metadata:
      labels:
        app: video-app
    spec:
      containers:
      - name: video-service
        image: hazemelagaty/video-service:2.1
        args:
        - bash
        - -c
        - sleep 10; java -jar ./target/Subscription-1.0-SNAPSHOT-jar-with-dependencies.jar;
        ports:
        - containerPort: 6380
      restartPolicy: Always
